### ISSUE TITLE
Toggle package does not work

### ISSUE THREAD

**Issue by ghost** [dmoonfire/atom-autocorrect#1]
This is a great package. I'm adapting it for use with a Velthuis transliteration system. It works well but I have a problem with toggling the package on and off. The keybinder for this does not seem to work. Do you have any idea how I can get the toggle to work? Thanks!

**Comment by dmoonfire** [comment]
Version 0.1.0 of the package should have this change. I took out the keybinding because other packages use it and I don't want to worry about collisions, but the menu items are there and you'll be able to bind to a key that you want.

As you mention adapting it, are you doing it via a plugin (like [autocorrect-en](https://github.com/dmoonfire/atom-autocorrect-en)) or modifying this package?

**Comment by ghost** [comment]
I'm indeed adapting it via the autocorrect-en plugin which I renamed to autocorrrect-velthuis. We are using it for the Velthuis transliteration system to type documents in sanskrit and pali easily. So not exactly the same scope as your original package but it works fine.

Thanks for the tip on the keybindings. Will have a look into that.

**Comment by dmoonfire** [comment]
That's exactly what I had in mind when I went with a plug in system. I have a local version that converts various romanizations into constructed language Unicode. It's hacky but works for my novel.

Best of luck!
